""" errors.py
"""

class PGPError(Exception):
    pass